language: ruby

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules

install:
    - bundle install --jobs=3 --retry=3
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rspec
    - nvm install node
    - node -v
    - npm install -g serverless
    - travis_retry npm install
    - pwd
    
    
environments:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEVELOPMENT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}


deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::739451191364:role/Admin"
  runtime: "ruby3.0.1"
  handler_name: "handler"


services:
  - postgresql
addons:
  postgresql: "9.6"
